spring:
  datasource:
    url: jdbc:postgresql://localhost/sweater
    username: postgres
    password: psql
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: false
  freemarker:
    expose-request-attributes: true
  mail:
    host: smtp.gmail.com
    username: email@gmail.com
    password: zekjpiybfwxfrgyg
    port: '465'
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  servlet:
    multipart:
      max-file-size: 5MB
server:
  port: 8090
#  profiles:
#    active: @spring.profiles.active@
upload:
  path: /Users/ivan/IdeaProjects/sweater/uploads
mail:
  debug: false
recaptcha:
  secret: 6LcBl60gAAAAAG82QAi15hOjvUmyJF1yBsR1p_HY